### ISSUE TITLE
reading capa rules errors

### ISSUE THREAD

**Issue by muteb** [marirs/capa-rs#1]
First of all I would like to thank you for the awesome effort to this project, well done!.

I keep getting errors when reading the capa rules . 

```
warn: rule capa-rules\anti-analysis\anti-debugging\debugger-detection\check-for-debugger-via-api.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\communication\ftp\send\send-file-using-ftp.yml error: InvalidRule(190, "property/write")
warn: rule capa-rules\communication\http\read-http-header.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\communication\http\set-http-header.yml error: InvalidRule(190, "property/write")
warn: rule capa-rules\communication\socket\tcp\create-tcp-socket.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\executable\resource\embed-dependencies-as-resources-using-fodycostura.yml error: InvalidRule(190, "namespace")
warn: rule capa-rules\host-interaction\file-system\get-common-file-path.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\file-system\meta\get-file-attributes.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\file-system\meta\get-file-size.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\file-system\meta\set-file-attributes.yml error: InvalidRule(190, "property/write")
warn: rule capa-rules\host-interaction\gui\enumerate-gui-resources.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\hardware\cpu\get-number-of-processors.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\hardware\storage\get-disk-information.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\hardware\storage\get-disk-size.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\network\domain\get-domain-information.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\os\hostname\get-hostname.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\process\create\create-a-process-with-modified-io-handles-and-window.yml error: InvalidRule(190, "property/write")
warn: rule capa-rules\host-interaction\process\modules\list\enumerate-process-modules.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\host-interaction\session\get-session-user-name.yml error: InvalidRule(190, "property/read")
Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (?-u)(?s)(?i)bcdedit(\.exe)?\s+/set\s+{default}\s+bootstatuspolicy\s+ignoreallfailures
                                           ^
error: repetition quantifier expects a valid decimal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)
warn: rule capa-rules\nursery\disable-automatic-windows-recovery-features.yml error: RegexError(Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (?-u)(?s)(?i)bcdedit(\.exe)?\s+/set\s+{default}\s+bootstatuspolicy\s+ignoreallfailures
                                           ^
error: repetition quantifier expects a valid decimal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
))
warn: rule capa-rules\nursery\extract-zip-archive.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\nursery\get-os-version-in-dotnet.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\nursery\get-process-image-filename.yml error: InvalidRule(190, "property/read")
warn: rule capa-rules\nursery\set-http-cookie.yml error: InvalidRule(190, "property/write")
warn: rule capa-rules\nursery\set-http-user-agent-in-dotnet.yml error: InvalidRule(190, "property/write")
thread '<unnamed>' panicked at 'no entry found for key', src\rules\mod.rs:811:23
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: core::panicking::panic_display<str>
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:72
   3: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:56
   4: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\option.rs:1874
   5: enum$<core::option::Option<ref$<ref$<capa::rules::Rule> > >, 1, 18446744073709551615, Some>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\option.rs:738
   6: std::collections::hash::map::impl$9::index
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\collections\hash\map.rs:1338
   7: capa::rules::get_rules_and_dependencies::rec
             at C:\Users\***\Documents\rust\capa-rs\src\rules\mod.rs:811
   8: capa::rules::get_rules_and_dependencies
             at C:\Users\***\Documents\rust\capa-rs\src\rules\mod.rs:816
   9: capa::rules::get_rules_for_scope
             at C:\Users\***\Documents\rust\capa-rs\src\rules\mod.rs:786
  10: capa::rules::get_basic_block_rules
             at C:\Users\***\Documents\rust\capa-rs\src\rules\mod.rs:762
  11: capa::rules::RuleSet::new
             at C:\Users\***\Documents\rust\capa-rs\src\rules\mod.rs:749
  12: capa::impl$0::from_file::closure$0
             at C:\Users\***\Documents\rust\capa-rs\src\lib.rs:48
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/lib.rs:50:48
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\result.rs:1805
   3: enum$<core::result::Result<enum$<core::result::Result<capa::rules::RuleSet,enum$<capa::error::Error> > >,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >::unwrap
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\result.rs:1098
   4: capa::FileCapabilities::from_file
             at C:\Users\***\Documents\rust\capa-rs\src\lib.rs:50
   5: capa_cli::main
             at C:\Users\***\Documents\rust\capa-rs\examples\capa_cli.rs:33
   6: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by marirs** [comment]
Hi - Thanks very much for your appreciation. 

Typically the Regex pattern python uses is slightly different from Rust. 
For eg: (?-u)(?s)(?i)bcdedit(\.exe)?\s+/set\s+{default}\s+bootstatuspolicy\s+ignoreallfailures

you just have to make it:
(?-u)(?s)(?i)bcdedit(\.exe)?\s+/set\s+\{default\}\s+bootstatuspolicy\s+ignoreallfailures

basically instead of { you will do \{ to make it Rust compatibly.

**Comment by muteb** [comment]
Oh thanks,
I also fixed "property/read" and "property/write" by adding the rule features type to the feature mod. I'm not really sure if I made it the correct way  but anyway I will push it your repo for review if you are keen.

**Comment by marirs** [comment]
please push it - I can verify it and if its fine, i can merge it as well.
Thanks so much

**Comment by muteb** [comment]
Done

**Comment by marirs** [comment]
Thanks

**Comment by marirs** [comment]
Thank you very much @muteb - i've published the release as well.
@mnaza - Thanks for verifying!
